// =========================================================================
// Configuration globale de l'application
// =========================================================================

// Etat global de l'application
global app_state;

app_state = struct();
app_state.theme_actuel = 1;
app_state.figure_interface = [];
app_state.figure_resultats = [];

// Initialiser ui_elements comme structure vide
app_state.ui_elements = struct();
app_state.ui_elements.popup_theme = [];
app_state.ui_elements.bouton_generer = [];
app_state.ui_elements.zone_interpretation = [];

// Parametres par defaut pour chaque theme
app_state.params = struct();

// Theme 1 : Audio Podcast
app_state.params.theme1 = struct(...
    'duree', 3, ...
    'f_ventilateur', 50, ...
    'f_sifflement', 8000, ...
    'niveau_bruit', 0.1);

// Theme 2 : Image Medicale
app_state.params.theme2 = struct(...
    'sigma_flou', 3, ...
    'niveau_bruit', 0.05, ...
    'taille_median', 3);

// Theme 3 : ECG
app_state.params.theme3 = struct(...
    'duree', 10, ...
    'freq_cardiaque', 70, ...
    'niveau_bruit', 0.2, ...
    'seuil_detection', 0.6);

// Theme 4 : Radar
app_state.params.theme4 = struct(...
    'distance', 2250, ...
    'snr_db', 10, ...
    'f_chirp_debut', 1000, ...
    'f_chirp_fin', 3000);

// Theme 5 : Liaison Radio
app_state.params.theme5 = struct(...
    'nb_bits', 20, ...
    'duree_bit', 0.1, ...
    'f_porteuse', 2000, ...
    'snr_db', 15);

// Metadonnees des themes
app_state.themes_liste = [...
    '1. Nettoyage Audio Podcast';
    '2. Amelioration Image Medicale';
    '3. Detection R-Peaks ECG';
    '4. Estimation Distance Radar';
    '5. Simulation Liaison Radio'];

// Configuration de l'interface
app_state.config_ui = struct(...
    'largeur', 1200, ...
    'hauteur', 700, ...
    'couleur_fond', [0.95 0.95 0.95], ...
    'couleur_titre', [0.2 0.4 0.7], ...
    'couleur_bouton', [0.2 0.7 0.3]);
